#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════
// ЭТАП 2: Генерация исторических географических границ для наций
//
// Вход:  data/nations.js, data/region_centroids.js
// Выход: data/nation_geo.js
//
// Для каждой нации без r-регионов:
//   - исторический bbox (lat_min, lat_max, lon_min, lon_max) в 304 BC
//   - приоритет (1=мелкий город, 10=империя) для разрешения перекрытий
//   - polygons: список sub-bbox для несмежных территорий
//   - capital_coords: координаты столицы (для проверки)
//
// Вызов: ANTHROPIC_API_KEY=sk-ant-... node scripts/stage2_gen_nation_geo.js
//
// Запускается БАТЧАМИ по 30 наций — результат дополняется, можно
// прерывать и продолжать.
// ═══════════════════════════════════════════════════════════════════

import fs   from 'fs';
import path from 'path';
import vm   from 'vm';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

const API_KEY = process.env.ANTHROPIC_API_KEY;
if (!API_KEY) {
  console.error('Установи ANTHROPIC_API_KEY');
  process.exit(1);
}

const MODEL      = 'claude-sonnet-4-6-20260218';
const MAX_TOKENS = 8000;
const BATCH_SIZE = 25;   // Наций за один запрос
const DELAY_MS   = 1000;

// ── Загрузка наций ────────────────────────────────────────────────
const nCode = fs.readFileSync(path.join(ROOT, 'data', 'nations.js'), 'utf8')
  .replace(/^const /mg, 'var ').replace(/^let /mg, 'var ');
const ns = vm.createContext({ console });
vm.runInContext(nCode, ns);
const NATIONS = ns.INITIAL_GAME_STATE?.nations ?? {};

// ── Загрузка существующих результатов (если есть) ─────────────────
const OUT_PATH = path.join(ROOT, 'data', 'nation_geo.js');
let existing = {};
if (fs.existsSync(OUT_PATH)) {
  try {
    const c = fs.readFileSync(OUT_PATH, 'utf8').replace(/^var /mg, 'var ');
    const s = vm.createContext({ console });
    vm.runInContext(c, s);
    existing = s.NATION_GEO ?? {};
    console.log(`Уже обработано: ${Object.keys(existing).length} наций`);
  } catch { existing = {}; }
}

// ── Нации которые нужно обработать ───────────────────────────────
// Все нации у которых нет r-формат регионов (r\d+)
function hasRRegions(nation) {
  return (nation.regions ?? []).some(r => /^r\d+$/.test(r));
}

const todo = Object.entries(NATIONS)
  .filter(([id, n]) => !hasRRegions(n) && !existing[id] && id !== 'neutral')
  .map(([id, n]) => ({
    id,
    government: n.government?.type ?? 'unknown',
    population: n.population?.total ?? 0,
    historical_note: n.historical_note?.slice(0, 120) ?? '',
    symbolic_regions: (n.regions ?? []).slice(0, 5), // Символические имена если есть
  }));

console.log(`Наций для обработки: ${todo.length}`);
if (todo.length === 0) {
  console.log('Все нации уже обработаны. data/nation_geo.js актуален.');
  process.exit(0);
}

// ── Сохранение промежуточных результатов ─────────────────────────
function saveResults(data) {
  const content = `// AUTO-GENERATED by scripts/stage2_gen_nation_geo.js
// Исторические географические границы наций для 304 BC
//
// Поля на нацию:
//   bbox: { latMin, latMax, lonMin, lonMax } — основная территория
//   polygons: [{latMin, latMax, lonMin, lonMax}] — несмежные части (опционально)
//   priority: 1-10 (1=маленький город, 10=империя) — для разрешения перекрытий
//   capital: { lat, lon } — примерные координаты столицы
//   notes: string — краткое обоснование
//
// Используется: scripts/stage3_assign_regions.js

var NATION_GEO = ${JSON.stringify(data, null, 2)};
`;
  fs.writeFileSync(OUT_PATH, content, 'utf8');
}

// ── Промпт ───────────────────────────────────────────────────────
function buildPrompt(nations) {
  const natList = nations.map(n =>
    `  ${n.id}: gov=${n.government}, pop=${n.population}, ` +
    `note="${n.historical_note}"` +
    (n.symbolic_regions.length ? `, symbolic_regions=[${n.symbolic_regions.join(',')}]` : '')
  ).join('\n');

  return {
    system: `Ты историко-географический эксперт по античному миру 304 года до н.э.
Отвечай ТОЛЬКО валидным JSON. Никакого текста вне JSON.`,
    user: `Список государств игры Pax Historia (304 BC, весь известный мир):

${natList}

Для каждого государства укажи его РЕАЛЬНЫЕ географические границы в 304 BC.
Верни JSON объект где ключ = ID государства:

{
  "<nation_id>": {
    "bbox": {
      "latMin": число,   // минимальная широта (юг)
      "latMax": число,   // максимальная широта (север)
      "lonMin": число,   // минимальная долгота (запад)
      "lonMax": число    // максимальная долгота (восток)
    },
    "polygons": [        // ОПЦИОНАЛЬНО: если территория несмежная
      { "latMin": ч, "latMax": ч, "lonMin": ч, "lonMax": ч }
    ],
    "priority": число,   // 1=маленький полис/племя, 5=среднее царство, 10=империя
    "capital": { "lat": число, "lon": число },
    "notes": "краткое обоснование в 1 предложение"
  }
}

ПРАВИЛА:
- bbox должен охватывать РЕАЛЬНУЮ территорию в 304 BC, не больше и не меньше
- Для мелких полисов (Спарта, Коринф, Родос) bbox ~0.5-2 градуса
- Для средних царств (Понт, Каппадокия) bbox ~3-8 градусов
- Для империй (Птолемеи, Селевкиды, Маурьи) bbox ~15-30 градусов
- priority: маленький город=1-2, полис с хорой=3-4, царство=5-7, великая держава=8-10
- Если государство имеет несмежные владения (острова+материк) — используй polygons
- Координаты: широта (lat) -90..90, долгота (lon) -180..180

Примеры ориентиров:
- Афины: lat 37.5-38.5, lon 22.5-24.5, priority=4
- Спарта: lat 36.5-37.5, lon 21.5-22.8, priority=3
- Египет Птолемеев: lat 22-32, lon 24-37, priority=9`
  };
}

// ── Вызов Claude API ─────────────────────────────────────────────
async function callClaude(system, user) {
  const body = {
    model: MODEL,
    max_tokens: MAX_TOKENS,
    temperature: 0,
    system,
    messages: [{ role: 'user', content: user }],
  };

  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const resp = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'x-api-key': API_KEY,
          'anthropic-version': '2023-06-01',
          'content-type': 'application/json',
        },
        body: JSON.stringify(body),
      });

      if (resp.status === 429) { await sleep(60_000); continue; }
      if (resp.status >= 500)  { await sleep(10_000 * (attempt + 1)); continue; }
      if (!resp.ok) throw new Error(`HTTP ${resp.status}: ${await resp.text()}`);

      const data = await resp.json();
      const raw  = data?.content?.[0]?.text ?? '';
      const cleaned = raw.replace(/^```json\s*/i,'').replace(/^```/,'').replace(/```$/,'').trim();
      return JSON.parse(cleaned);
    } catch (e) {
      if (attempt === 2) throw e;
      await sleep(5000);
    }
  }
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// ── Основной цикл по батчам ───────────────────────────────────────
const results = { ...existing };
const batches = [];
for (let i = 0; i < todo.length; i += BATCH_SIZE) {
  batches.push(todo.slice(i, i + BATCH_SIZE));
}

console.log(`Батчей: ${batches.length} по ~${BATCH_SIZE} наций`);
console.log('─'.repeat(50));

for (let bi = 0; bi < batches.length; bi++) {
  const batch = batches[bi];
  const ids = batch.map(n => n.id);
  console.log(`\nБатч ${bi + 1}/${batches.length}: ${ids.join(', ')}`);

  try {
    const { system, user } = buildPrompt(batch);
    const geoData = await callClaude(system, user);

    let added = 0;
    for (const [id, geo] of Object.entries(geoData)) {
      if (!geo?.bbox) {
        console.warn(`  ⚠ ${id}: нет bbox — пропускаю`);
        continue;
      }
      // Валидация bbox
      const { latMin, latMax, lonMin, lonMax } = geo.bbox;
      if (latMin >= latMax || lonMin >= lonMax) {
        console.warn(`  ⚠ ${id}: некорректный bbox — пропускаю`);
        continue;
      }
      results[id] = geo;
      added++;
    }
    console.log(`  ✓ Получено: ${added}/${batch.length} наций`);

    // Сохраняем после каждого батча
    saveResults(results);
    console.log(`  Сохранено: ${Object.keys(results).length} наций суммарно`);

  } catch (e) {
    console.error(`  ✗ Батч ${bi + 1} не удался: ${e.message}`);
    console.error('  Промежуточные результаты сохранены. Перезапусти скрипт.');
    saveResults(results);
    process.exit(1);
  }

  if (bi < batches.length - 1) await sleep(DELAY_MS);
}

// ── Итог ─────────────────────────────────────────────────────────
console.log('\n' + '═'.repeat(50));
console.log(`✓ Этап 2 завершён`);
console.log(`  Обработано наций: ${Object.keys(results).length}`);
console.log(`  Файл: data/nation_geo.js`);

// Статистика приоритетов
const byPriority = {};
for (const geo of Object.values(results)) {
  const p = geo.priority ?? 0;
  byPriority[p] = (byPriority[p] ?? 0) + 1;
}
console.log('\nРаспределение по приоритету:');
for (const [p, c] of Object.entries(byPriority).sort((a,b)=>+a[0]-+b[0])) {
  console.log(`  priority=${p}: ${c} наций`);
}
console.log('\nСледующий: node scripts/stage3_assign_regions.js');
