// agents/file_io.js — загрузка входных файлов и запись выхода

import fs   from 'fs';
import path from 'path';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import vm from 'vm';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR  = path.join(__dirname, '..', 'data');

// ─── Загрузка одного .js файла через vm.createContext ───────────────────────

function loadFile(filename) {
  const filePath = path.join(DATA_DIR, filename);
  let content = fs.readFileSync(filePath, 'utf8');
  // allow const/let declarations to be shared across files in the same context
  content = content
    .replace(/^const /mg, 'var ')
    .replace(/^let /mg,   'var ');
  return content;
}

// ─── loadAllInputs ───────────────────────────────────────────────────────────

export function loadAllInputs() {
  // Порядок важен: nations.js должен быть первым, regions_data.js вторым
  // (regions_data.js мутирует INITIAL_GAME_STATE.regions из nations.js)
  const orderedFiles = [
    'nations.js',
    'regions_data.js',
    'goods.js',
    'buildings.js',
    'social_classes.js',
    'biomes.js',
    'laws_labor.js',
    'goods_meta.js',
    'pdf_chains.js',
  ];

  const sandbox = vm.createContext({ console });

  for (const filename of orderedFiles) {
    try {
      const code = loadFile(filename);
      vm.runInContext(code, sandbox);
    } catch (e) {
      throw new Error(`Не удалось загрузить ${filename}: ${e.message}`);
    }
  }

  // Извлекаем переменные из sandbox
  // nations.js хранит нации внутри INITIAL_GAME_STATE
  const NATIONS = sandbox.INITIAL_GAME_STATE?.nations ?? sandbox.NATIONS ?? {};
  // regions_data.js мутирует INITIAL_GAME_STATE.regions
  const REGIONS_DATA_extracted = sandbox.INITIAL_GAME_STATE?.regions ?? {};

  return {
    GOODS:          sandbox.GOODS,
    BUILDINGS:      sandbox.BUILDINGS,
    SOCIAL_CLASSES: sandbox.SOCIAL_CLASSES,
    REGIONS_DATA:   REGIONS_DATA_extracted,
    BIOME_META:     sandbox.BIOME_META,
    NATIONS,
    LAWS_LABOR:     sandbox.LAWS_LABOR,
    GOODS_META:     sandbox.GOODS_META,
    PDF_CHAINS:     sandbox.PDF_CHAINS,
  };
}

// ─── loadExistingChains ──────────────────────────────────────────────────────

export function loadExistingChains() {
  const filePath = path.join(DATA_DIR, 'chains_data.js');
  if (!fs.existsSync(filePath)) return {};

  const content = fs.readFileSync(filePath, 'utf8').trim();
  if (!content) return {};

  try {
    const sandbox = vm.createContext({ console });
    vm.runInContext(content, sandbox);
    return sandbox.CHAINS_DATA ?? {};
  } catch (e) {
    return {};
  }
}

// ─── appendChain ─────────────────────────────────────────────────────────────
// Формат файла:
//   var CHAINS_DATA = {
//     "wheat": { ... },
//   };

export function appendChain(goodId, chainData) {
  const filePath = path.join(DATA_DIR, 'chains_data.js');
  const entry = `  ${JSON.stringify(goodId)}: ${JSON.stringify(chainData, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : '  ' + line))
    .join('\n')},\n`;

  if (!fs.existsSync(filePath)) {
    // Первая запись — создаём файл с шапкой
    const header = [
      '// AUTO-GENERATED by agents/chain_builder.js',
      `// Дата: ${new Date().toISOString()}`,
      '// Не редактировать вручную',
      '',
      'var CHAINS_DATA = {',
      '',
    ].join('\n');
    fs.writeFileSync(filePath, header + entry + '};\n', 'utf8');
    return;
  }

  // Вставляем перед закрывающей скобкой
  let current = fs.readFileSync(filePath, 'utf8');
  const lastBrace = current.lastIndexOf('\n};');
  if (lastBrace === -1) {
    // Файл повреждён — перезаписываем с нуля
    const header = [
      '// AUTO-GENERATED by agents/chain_builder.js',
      `// Дата: ${new Date().toISOString()}`,
      '// Не редактировать вручную',
      '',
      'var CHAINS_DATA = {',
      '',
    ].join('\n');
    fs.writeFileSync(filePath, header + entry + '};\n', 'utf8');
    return;
  }

  const updated = current.slice(0, lastBrace + 1) + '\n' + entry + '};\n';
  fs.writeFileSync(filePath, updated, 'utf8');
}

// ─── logError ────────────────────────────────────────────────────────────────

export function logError(goodId, error, context) {
  const logPath = path.join(__dirname, '..', 'chains_errors.log');
  const ts = new Date().toISOString();
  const errorStr = Array.isArray(error) ? error.join('; ') : String(error);
  const line = `[${ts}] [${goodId}] [${errorStr}] [${context}]\n`;
  fs.appendFileSync(logPath, line, 'utf8');
}
