// agents/file_io.js — загрузка входных файлов и запись выхода

import fs   from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import vm from 'vm';

const __dirname  = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR   = path.join(__dirname, '..', 'data');
const BACKUP_DIR = path.join(DATA_DIR, 'backups');
const CHAINS_FILE = path.join(DATA_DIR, 'chains_data.js');
const CHAINS_TMP  = path.join(DATA_DIR, 'chains_data.tmp.js');

// Порог резервного копирования: каждые N цепочек
const BACKUP_EVERY = 5;

// ─── Загрузка одного .js файла через vm.createContext ───────────────────────

function loadFile(filename) {
  const filePath = path.join(DATA_DIR, filename);
  let content = fs.readFileSync(filePath, 'utf8');
  // allow const/let declarations to be shared across files in the same context
  content = content
    .replace(/^const /mg, 'var ')
    .replace(/^let /mg,   'var ');
  return content;
}

// ─── loadAllInputs ───────────────────────────────────────────────────────────

export function loadAllInputs() {
  // Порядок важен: nations.js должен быть первым, regions_data.js вторым
  // (regions_data.js мутирует INITIAL_GAME_STATE.regions из nations.js)
  const orderedFiles = [
    'nations.js',
    'regions_data.js',
    'goods.js',
    'buildings.js',
    'social_classes.js',
    'biomes.js',
    'laws_labor.js',
    'goods_meta.js',
    'goods_labor.js',
    'deposit_map.js',
    'pdf_chains.js',
  ];

  const sandbox = vm.createContext({ console });

  for (const filename of orderedFiles) {
    try {
      const code = loadFile(filename);
      vm.runInContext(code, sandbox);
    } catch (e) {
      throw new Error(`Не удалось загрузить ${filename}: ${e.message}`);
    }
  }

  // Извлекаем переменные из sandbox
  // nations.js хранит нации внутри INITIAL_GAME_STATE
  const NATIONS = sandbox.INITIAL_GAME_STATE?.nations ?? sandbox.NATIONS ?? {};
  // regions_data.js мутирует INITIAL_GAME_STATE.regions
  const REGIONS_DATA_extracted = sandbox.INITIAL_GAME_STATE?.regions ?? {};

  return {
    GOODS:          sandbox.GOODS,
    BUILDINGS:      sandbox.BUILDINGS,
    SOCIAL_CLASSES: sandbox.SOCIAL_CLASSES,
    REGIONS_DATA:   REGIONS_DATA_extracted,
    BIOME_META:     sandbox.BIOME_META,
    NATIONS,
    LAWS_LABOR:     sandbox.LAWS_LABOR,
    GOODS_META:     sandbox.GOODS_META,
    GOODS_LABOR:    sandbox.GOODS_LABOR    ?? {},
    DEPOSIT_MAP:    sandbox.DEPOSIT_MAP    ?? {},
    PDF_CHAINS:     sandbox.PDF_CHAINS,
  };
}

// ─── loadExistingChains ──────────────────────────────────────────────────────

export function loadExistingChains() {
  const filePath = path.join(DATA_DIR, 'chains_data.js');
  if (!fs.existsSync(filePath)) return {};

  const content = fs.readFileSync(filePath, 'utf8').trim();
  if (!content) return {};

  try {
    const sandbox = vm.createContext({ console });
    vm.runInContext(content, sandbox);
    return sandbox.CHAINS_DATA ?? {};
  } catch (e) {
    return {};
  }
}

// ─── appendChain ─────────────────────────────────────────────────────────────
// Атомарная запись: tmp → validate → rename + бэкап каждые BACKUP_EVERY цепочек.

function buildChainsFileContent(chains) {
  const header = [
    '// AUTO-GENERATED by agents/chain_builder.js',
    `// Дата: ${new Date().toISOString()}`,
    '// Не редактировать вручную',
    '',
    'var CHAINS_DATA = {',
    '',
  ].join('\n');

  const entries = Object.entries(chains)
    .map(([id, data]) =>
      `  ${JSON.stringify(id)}: ${JSON.stringify(data, null, 2)
        .split('\n')
        .map((line, i) => (i === 0 ? line : '  ' + line))
        .join('\n')},`
    )
    .join('\n');

  return header + entries + '\n\n};\n';
}

function validateChainsFile(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const sandbox = vm.createContext({ console });
    vm.runInContext(content, sandbox);
    if (!sandbox.CHAINS_DATA || typeof sandbox.CHAINS_DATA !== 'object')
      throw new Error('CHAINS_DATA не является объектом');
    return true;
  } catch (e) {
    return false;
  }
}

function ensureBackupDir() {
  if (!fs.existsSync(BACKUP_DIR)) fs.mkdirSync(BACKUP_DIR, { recursive: true });
}

export function appendChain(goodId, chainData) {
  // Загружаем текущее состояние
  const current = loadExistingChains();
  current[goodId] = chainData;

  const newContent = buildChainsFileContent(current);

  // Пишем во временный файл
  fs.writeFileSync(CHAINS_TMP, newContent, 'utf8');

  // Валидируем временный файл
  if (!validateChainsFile(CHAINS_TMP)) {
    fs.unlinkSync(CHAINS_TMP);
    throw new Error(`appendChain(${goodId}): tmp-файл не прошёл валидацию`);
  }

  // Атомарный переход: rename (атомарно на одном диске)
  fs.renameSync(CHAINS_TMP, CHAINS_FILE);

  // Бэкап каждые BACKUP_EVERY цепочек
  const count = Object.keys(current).length;
  if (count % BACKUP_EVERY === 0) {
    ensureBackupDir();
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    fs.copyFileSync(CHAINS_FILE, path.join(BACKUP_DIR, `chains_${count}_${ts}.js`));
  }
}

// ─── logError ────────────────────────────────────────────────────────────────

export function logError(goodId, error, context) {
  const logPath = path.join(__dirname, '..', 'chains_errors.log');
  const ts = new Date().toISOString();
  const errorStr = Array.isArray(error) ? error.join('; ') : String(error);
  const line = `[${ts}] [${goodId}] [${errorStr}] [${context}]\n`;
  fs.appendFileSync(logPath, line, 'utf8');
}
